name: Android CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          profile: Nexus 5
          script: |
            echo "no" | sdkmanager --install "system-images;android-30;default;x86_64"
            echo "no" | avdmanager create avd --force --name test --abi default/x86_64 --package "system-images;android-30;default;x86_64"
            emulator -avd test -no-window -no-audio &
            android-wait-for-emulator
            adb shell input keyevent 82

      - name: Build with Gradle
        run: ./gradlew build

      - name: Launch unit tests with Gradle
        run: ./gradlew test

      - name: Run instrumented tests with Gradle
        run: ./gradlew connectedCheck
